// Auto-generated signup reference data — kept in sync with the iOS app's SignupData.swift
// universities: hipolabs world-universities (TR); cities: 81 TR provinces.

export const universities: string[] = [
  "Abant Izzet Baysal University",
  "Abdullah Gul University",
  "Acibadem University",
  "Adana Alparslan Turkes University",
  "Adana Science and Technology University",
  "Adiyaman University",
  "Adnan Menderes University",
  "Afyon Kocatepe University",
  "Agri Ibrahim Cecen University",
  "Ahi Evran University",
  "Air Force Academy",
  "Akdeniz University",
  "Aksaray University",
  "Alanya Alaaddin Keykubat University",
  "Alanya Hamdullah Emin Pasa University",
  "Amasya University",
  "Anadolu University",
  "Ankara Haci Bayram Veli University",
  "Ankara Medipol University",
  "Ankara Science University",
  "Ankara Social Science University",
  "Ankara University",
  "Ankara Yildirim Beyazit University",
  "Antalya Bilim University",
  "Ardahan University",
  "Artvin Coruh University",
  "Atatürk University",
  "Atilim University",
  "Avrasya University",
  "Bahcesehir University",
  "Balikesir University",
  "Bandirma ONYEDI Eylul University",
  "Bartin University",
  "Baskent University",
  "Batman University",
  "Bayburt University",
  "Beykent University",
  "Bezmialem Vakif University",
  "Bilecik University",
  "Bilkent University",
  "Bingol University",
  "Biruni University",
  "Bitlis Eren University",
  "Boğaziçi University",
  "Bozok University",
  "Bulent Ecevit University",
  "Bursa Technical University",
  "Cag University",
  "Canakkale (18th March) University",
  "Cankaya University",
  "Cankiri Karatekin University",
  "Celal Bayar University",
  "Cukurova University",
  "Dicle (Tirgris) University",
  "Dogus University",
  "Dokuz Eylül University",
  "Dumlupinar University",
  "Duzce University",
  "Ege University",
  "Erciyes University",
  "Erzincan Binali Yildirim University",
  "Erzurum Technical University",
  "Eskisehir Osmangazi University",
  "Eskisehir Technical University",
  "Fatih Sultan Mehmet University",
  "Fenerbahce University",
  "Firat (Euphrates) University",
  "Galatasaray University",
  "Gazi University Ankara",
  "Gaziantep University",
  "Gaziosmanpasa University",
  "Gebze Institute of Technology",
  "Gebze Technical University",
  "Giresun University",
  "Gulhane Military Medical Academy",
  "Gumushane University",
  "Hacettepe University",
  "Hakkari University",
  "Halic University",
  "Harran University",
  "Hasan Kalyoncu University",
  "Health Sciences University",
  "Hitit University",
  "Igdir University",
  "Inönü University",
  "Isik University",
  "Iskenderun Technical University",
  "Istanbul 29 Mayis University",
  "Istanbul Arel University",
  "Istanbul Aydin University",
  "Istanbul Bilgi University",
  "Istanbul Esenyurt University",
  "Istanbul Gedik University",
  "Istanbul Gelisim University",
  "Istanbul Kemerburgaz University",
  "Istanbul Kultur University",
  "Istanbul Medeniyet University",
  "Istanbul Medipol University",
  "Istanbul Rumeli University",
  "Istanbul Sabahattin Zaim University",
  "Istanbul Technical University",
  "Istanbul Ticaret University",
  "Istanbul Topkapi University",
  "Istanbul University",
  "Istinye University",
  "Izmir Bakırçay University",
  "Izmir Democracy University",
  "Izmir Institute of Technology",
  "Izmir Katip Celebi University",
  "Izmir Tınaztepe University",
  "İzmir University of Economics",
  "Kadir Has University",
  "Kafkas University",
  "Kahramanmaras Sutcu İmam University",
  "Karabuk University",
  "Karadeniz Technical University",
  "karamanoglu mehmet bey University",
  "Karatay University",
  "Kastamonu University",
  "Kilis 7 Aralık University",
  "Kirikkale University",
  "Kirklareli University",
  "Kocaeli University",
  "Koç University",
  "Konya Gida Tarim University",
  "Konya Technical University",
  "Maltepe University",
  "Mardin Artuklu University",
  "Marmara University",
  "MEF University",
  "Mehmet Akif Ersoy University",
  "Mersin University",
  "Middle East Technical University",
  "Mimar Sinan Fine Arts University",
  "Mimar Sinan University",
  "Mugla Sitki Kocman University",
  "Mus Alparslan University",
  "Mustafa Kemal University",
  "Namik Kemal University",
  "Necmettin Erbakan University",
  "Nevsehir Haci Bektas Veli University",
  "Nigde Omer Halisdemir University",
  "Nisantasi University",
  "Nuh Naci Yazgan University",
  "Okan University",
  "Omer Halisdemir University",
  "Ondokuz Mayıs University",
  "Ordu University",
  "Osmaniye Korkut Ata University",
  "OSTIM Technical University",
  "Ozyegin University",
  "Pamukkale University",
  "Piri Reis University",
  "Recep Tayip Erdogan University",
  "Sabanci University",
  "Sakarya University",
  "Sakarya Uygulamalı Bilimler Üniversitesi",
  "Samsun University",
  "Sanko University",
  "Selcuk University",
  "Siirt University",
  "Sinop University",
  "Sirnak University",
  "Sivas Cumhuriyet University",
  "Suleyman Demirel University",
  "Tarsus University",
  "TED University",
  "Tobb Economics and Technology University",
  "Toros University",
  "Trakya University",
  "Tunceli University",
  "Turkish Naval Academy",
  "Türkisch-Deutsche Universität",
  "Ufuk University",
  "Uludag University",
  "University of Kyrenia",
  "University of Turkish Aeronautical Association",
  "Usak University",
  "Uskudar University",
  "Yalova University",
  "Yasar University",
  "Yeditepe University",
  "Yeni Yuzyil University",
  "Yildirim Beyazit University",
  "Yildiz Technical University",
  "Yuksek ihtisas University",
  "Yüzüncü Yil (Centennial) University",
  "Zonguldak Karaelmas University",
];

export const cities: string[] = [
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Aksaray",
  "Amasya",
  "Ankara",
  "Antalya",
  "Ardahan",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bartın",
  "Batman",
  "Bayburt",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Düzce",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkâri",
  "Hatay",
  "Iğdır",
  "Isparta",
  "İstanbul",
  "İzmir",
  "Kahramanmaraş",
  "Karabük",
  "Karaman",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırıkkale",
  "Kırklareli",
  "Kırşehir",
  "Kilis",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Mardin",
  "Mersin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Osmaniye",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Şanlıurfa",
  "Şırnak",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Uşak",
  "Van",
  "Yalova",
  "Yozgat",
  "Zonguldak",
];

export const countries: string[] = [
  "Türkiye",
  "KKTC",
  "Almanya",
  "Amerika Birleşik Devletleri",
  "Avusturya",
  "Azerbaycan",
  "Belçika",
  "Birleşik Krallık",
  "Fransa",
  "Hollanda",
  "İspanya",
  "İsveç",
  "İsviçre",
  "İtalya",
  "Kanada",
  "Diğer",
];

export const departments: string[] = [
  "Bilgisayar Mühendisliği",
  "Yazılım Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Endüstri Mühendisliği",
  "Makine Mühendisliği",
  "İnşaat Mühendisliği",
  "Kimya Mühendisliği",
  "Gıda Mühendisliği",
  "Çevre Mühendisliği",
  "Biyomedikal Mühendisliği",
  "Mekatronik Mühendisliği",
  "Metalurji ve Malzeme Mühendisliği",
  "Havacılık ve Uzay Mühendisliği",
  "Harita Mühendisliği",
  "Jeoloji Mühendisliği",
  "Ziraat Mühendisliği",
  "Tıp",
  "Diş Hekimliği",
  "Eczacılık",
  "Hemşirelik",
  "Fizyoterapi ve Rehabilitasyon",
  "Beslenme ve Diyetetik",
  "Veteriner",
  "Hukuk",
  "İşletme",
  "İktisat",
  "Maliye",
  "Muhasebe",
  "Bankacılık ve Finans",
  "Uluslararası İlişkiler",
  "Siyaset Bilimi ve Kamu Yönetimi",
  "Psikoloji",
  "Sosyoloji",
  "Felsefe",
  "Tarih",
  "Coğrafya",
  "Sanat Tarihi",
  "Arkeoloji",
  "Mimarlık",
  "İç Mimarlık",
  "Şehir ve Bölge Planlama",
  "Endüstriyel Tasarım",
  "Grafik Tasarım",
  "Matematik",
  "Fizik",
  "Kimya",
  "Biyoloji",
  "Moleküler Biyoloji ve Genetik",
  "İstatistik",
  "Türk Dili ve Edebiyatı",
  "İngiliz Dili ve Edebiyatı",
  "İngilizce Öğretmenliği",
  "Sınıf Öğretmenliği",
  "Okul Öncesi Öğretmenliği",
  "Rehberlik ve Psikolojik Danışmanlık",
  "Gazetecilik",
  "Halkla İlişkiler ve Tanıtım",
  "Radyo Televizyon ve Sinema",
  "Turizm İşletmeciliği",
  "Gastronomi ve Mutfak Sanatları",
  "Beden Eğitimi ve Spor",
  "Diğer",
];

